name: Update Database from Release

on:
  release:
    types: [published]  # 监听 Release 发布事件

jobs:
  update-database:
    runs-on: ubuntu-latest  # 选择运行环境

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Download database from the release
      run: |
        # 获取最新的 Release 下载链接
        curl -L -o project_new.db https://github.com/bagman2023/survey/releases/download/v1.0.0/project_new.db

    - name: Replace database in the repository
      run: |
        # 将下载的数据库替换到仓库中正确的位置
        mv project_new.db ./project_new.db  # 这里使用仓库根目录下的路径替换

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7  # 使用 add-and-commit 动作自动提交和推送更新
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update project_new.db to the latest version from release'
        branch: main  # 根据你仓库的分支调整
